
[network]
name = "hoodi-testnet"
chain_id = 560048
rpc_url = "https://ethereum-hoodi-rpc.publicnode.com"

[traps.SimpleMintTrap]
enabled = true
params = { max_mints_per_block = 5 }
whitelist = ["0xb0302ad164aaBa82986025cBC9c3323bA85BE909"]
